site_name: HomematicIP Cloud Rest API Wrapper
site_description: A Python wrapper for the homematicIP REST API.
site_url: https://hahn-th.github.io/homematicip-rest-api/
repo_url: https://github.com/hahn-th/homematicip-rest-api
repo_name: hahn-th/homematicip-rest-api

nav:
- Home:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Batch testing: batch-testing.md
  - Changelog: changelog.md
- API Reference:
  - Introduction: api-introduction.md

theme:
  name: material
  palette:
    primary: light-blue
  features:
  - navigation.expand
  - navigation.footer
  - navigation.instant.preview
  - navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
plugins:
- search
- mkdocstrings:
    enable_inventory: true
    default_handler: python
    handlers:
      python:
        inventories:
          - https://docs.python.org/3/objects.inv
        options:
          docstring_section_style: table
          docstring_style: sphinx
          #filters: ["!^_"]
          heading_level: 1
          merge_init_into_class: false
          parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_signature_annotations: true
          show_signature: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_submodules: false
          summary: false
          show_source: false
          load_external_modules: false
          members_order: alphabetical
- api-autonav:
    modules: ['src/homematicip']
    nav_section_title: "API Reference"
    api_root_uri: "reference"
#    nav_item_prefix: "<code class='doc-symbol doc-symbol-nav doc-symbol-module'></code>"
    nav_item_prefix: ""
    #exclude_private: false
    on_implicit_namespace_package: "skip"
    exclude:
      - "homematicip._version"
      - "homematicip.__main__"