import logging

LOGGER = logging.getLogger(__name__)

LOGGER.warn(
    "constants.py is deprecated. Please use the corresponding enums in enums.py"
)

# DEVICES
DEVICE = "DEVICE"
FULL_FLUSH_SHUTTER = "FULL_FLUSH_SHUTTER"
PLUGABLE_SWITCH = "PLUGABLE_SWITCH"
KEY_REMOTE_CONTROL_ALARM = "KEY_REMOTE_CONTROL_ALARM"
MOTION_DETECTOR_INDOOR = "MOTION_DETECTOR_INDOOR"
ALARM_SIREN_INDOOR = "ALARM_SIREN_INDOOR"
PUSH_BUTTON = "PUSH_BUTTON"
TEMPERATURE_HUMIDITY_SENSOR_DISPLAY = "TEMPERATURE_HUMIDITY_SENSOR_DISPLAY"
PLUGABLE_SWITCH_MEASURING = "PLUGABLE_SWITCH_MEASURING"
FLOOR_TERMINAL_BLOCK_6 = "FLOOR_TERMINAL_BLOCK_6"
SMOKE_DETECTOR = "SMOKE_DETECTOR"
WALL_MOUNTED_THERMOSTAT_PRO = "WALL_MOUNTED_THERMOSTAT_PRO"
SHUTTER_CONTACT = "SHUTTER_CONTACT"
SHUTTER_CONTACT_INTERFACE = "SHUTTER_CONTACT_INTERFACE"
HEATING_THERMOSTAT = "HEATING_THERMOSTAT"
SHUTTER_CONTACT_INVISIBLE = "SHUTTER_CONTACT_INVISIBLE"
BRAND_WALL_MOUNTED_THERMOSTAT = "BRAND_WALL_MOUNTED_THERMOSTAT"
TEMPERATURE_HUMIDITY_SENSOR = "TEMPERATURE_HUMIDITY_SENSOR"
BRAND_SHUTTER = "BRAND_SHUTTER"
PRECENCE_DETECTOR_INDOOR = "PRECENCE_DETECTOR_INDOOR"
PLUGGABLE_DIMMER = "PLUGGABLE_DIMMER"
BRAND_DIMMER = "BRAND_DIMMER"
BRAND_SWITCH_MEASURING = "BRAND_SWITCH_MEASURING"
PRINTED_CIRCUIT_BOARD_SWITCH_BATTERY = "PRINTED_CIRCUIT_BOARD_SWITCH_BATTERY"
ROOM_CONTROL_DEVICE = "ROOM_CONTROL_DEVICE"
TEMPERATURE_HUMIDITY_SENSOR_OUTDOOR = "TEMPERATURE_HUMIDITY_SENSOR_OUTDOOR"
WEATHER_SENSOR = "WEATHER_SENSOR"
WEATHER_SENSOR_PRO = "WEATHER_SENSOR_PRO"
ROTARY_HANDLE_SENSOR = "ROTARY_HANDLE_SENSOR"
FULL_FLUSH_SWITCH_MEASURING = "FULL_FLUSH_SWITCH_MEASURING"
MOTION_DETECTOR_PUSH_BUTTON = "MOTION_DETECTOR_PUSH_BUTTON"
WATER_SENSOR = "WATER_SENSOR"
SHUTTER_CONTACT_MAGNETIC = "SHUTTER_CONTACT_MAGNETIC"
TORMATIC_MODULE = "TORMATIC_MODULE"


# GROUPS
EXTENDED_LINKED_SHUTTER = "EXTENDED_LINKED_SHUTTER"
SHUTTER_WIND_PROTECTION_RULE = "SHUTTER_WIND_PROTECTION_RULE"
LOCK_OUT_PROTECTION_RULE = "LOCK_OUT_PROTECTION_RULE"
SMOKE_ALARM_DETECTION_RULE = "SMOKE_ALARM_DETECTION_RULE"
OVER_HEAT_PROTECTION_RULE = "OVER_HEAT_PROTECTION_RULE"
SWITCHING_PROFILE = "SWITCHING_PROFILE"
HEATING_COOLING_DEMAND_PUMP = "HEATING_COOLING_DEMAND_PUMP"
HEATING_COOLING_DEMAND_BOILER = "HEATING_COOLING_DEMAND_BOILER"
HEATING_DEHUMIDIFIER = "HEATING_DEHUMIDIFIER"
HEATING_EXTERNAL_CLOCK = "HEATING_EXTERNAL_CLOCK"
HEATING_COOLING_DEMAND = "HEATING_COOLING_DEMAND"
HEATING = "HEATING"
SECURITY_ZONE = "SECURITY_ZONE"
INBOX = "INBOX"
HEATING_CHANGEOVER = "HEATING_CHANGEOVER"
HEATING_TEMPERATURE_LIMITER = "HEATING_TEMPERATURE_LIMITER"
HEATING_HUMIDITY_LIMITER = "HEATING_HUMIDITY_LIMITER"
ALARM_SWITCHING = "ALARM_SWITCHING"
LINKED_SWITCHING = "LINKED_SWITCHING"
EXTENDED_LINKED_SWITCHING = "EXTENDED_LINKED_SWITCHING"
SWITCHING = "SWITCHING"
SECURITY = "SECURITY"
ENVIRONMENT = "ENVIRONMENT"

# Security Events
SENSOR_EVENT = "SENSOR_EVENT"
ACCESS_POINT_DISCONNECTED = "ACCESS_POINT_DISCONNECTED"
ACCESS_POINT_CONNECTED = "ACCESS_POINT_CONNECTED"
ACTIVATION_CHANGED = "ACTIVATION_CHANGED"
SILENCE_CHANGED = "SILENCE_CHANGED"

# Automation Rules
SIMPLE_RULE = "SIMPLE"

# Functional Homes
INDOOR_CLIMATE = "INDOOR_CLIMATE"
LIGHT_AND_SHADOW = "LIGHT_AND_SHADOW"
SECURITY_AND_ALARM = "SECURITY_AND_ALARM"
WEATHER_AND_ENVIRONMENT = "WEATHER_AND_ENVIRONMENT"
